name: TUF-on-CI publish

permissions: {}

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: false

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - id: build-and-upload-repository
        uses: kipz/tuf-on-ci/actions/upload-repository@a611f4d943880497a6f5f4fc0d0db841c60eb593 # v0.7.0
        with:
          gh_pages: true
          ref: ${{ inputs.ref }}

  deploy-to-pages:
    permissions:
      pages: write
      id-token: write # for authenticating to GH Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy TUF-on-CI repository to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5

  test-deployed-repository:
    needs: deploy-to-pages
    permissions:
      contents: read # for checking out the repository
      issues: write # for modifying Issues
    uses: ./.github/workflows/test.yml

  update-issue:
    runs-on: ubuntu-latest
    needs: [build, deploy-to-pages, test-deployed-repository]
    if: always() && !cancelled()
    permissions:
      issues: write # for modifying Issues
    steps:
      - name: Update the issue for the workflow
        uses: kipz/tuf-on-ci/actions/update-issue@a611f4d943880497a6f5f4fc0d0db841c60eb593 # v0.7.0
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          success: ${{ !contains(needs.*.result, 'failure') }}
