name: TUF-on-CI repository tests

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '17 4,10,16,22 * * *'

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checking out the repository
    steps:
      - name: Smoke test TUF-on-CI repository with a TUF client
        uses: kipz/tuf-on-ci/actions/test-repository@a611f4d943880497a6f5f4fc0d0db841c60eb593 # v0.7.0

  update-issue:
    runs-on: ubuntu-latest
    needs: [smoke-test]
    # During workflow_call, caller updates issue
    if: always() && !cancelled() && github.workflow == 'TUF-on-CI repository tests'
    permissions:
      issues: write # for modifying Issues
    steps:
      - name: Update the issue for the workflow
        uses: kipz/tuf-on-ci/actions/update-issue@a611f4d943880497a6f5f4fc0d0db841c60eb593 # v0.7.0
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          success: ${{ !contains(needs.*.result, 'failure') }}
